name: Publish distributions ğŸ“¦ Test ğŸšš

on:
  workflow_dispatch:

jobs:
  build-n-publish-test:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    steps:
      # å‡çº§åˆ° v4
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      # å‡çº§åˆ° v5
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install pypa/build
      run: python -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .
      
    - name: Publish distribution to Test PyPI
      # å‡çº§åˆ° v1
      uses: pypa/gh-action-pypi-publish@v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
